### PR TITLE
Enhancement: Normalize composer.json

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] requires `localheinz/composer-normalize`
* [x] runs `composer normalize --dry-run` on Travis
* [x] normalizes `composer.json`

💁‍♂️ For reference, see 

* https://github.com/localheinz/composer-normalize
* https://localheinz.com/blog/2018/01/15/normalizing-composer.json/

### CODE REVIEW

**Comment by derrabus** [comment]
If we take that road, I'd suggest to make sure that composer files remain normalized. I have opened a feature request localheinz/composer-normalize#29 for that purpose.

**Comment by localheinz** [comment]
@derrabus 

Because of https://github.com/localheinz/composer-normalize/pull/30 I require `php:^7.1`, so for now we can't use `localheinz/composer-normalize` as a direct development dependency, unless we drop support for PHP 7.0.

**Comment by derrabus** [comment]
@localheinz I see. But you could do the validation on the php 7.1 Travis run only.

**Comment by chartjes** [comment]
Thanks @localheinz and @derrabus

**Comment by localheinz** [comment]
Thank you, @chartjes!

**Pull request merged**
