### PR TITLE
Display Additional Airport Information in Admin Interface

### PR DESCRIPTION
**Pull request by mdwheele**
Related: #280 

This PR introduces a value object for Airport Information (`AirportInfo`). This includes the airport's IATA code, name and country. The work includes a new interface for retrieving airport information by IATA code as well as an implementation using `illuminate/database`. Airport information is shown as part of the admin interface to all speakers as well as on each speaker profile page:

image

This PR also adds the ability to migrate an in-memory Sqlite3 database using Phinx and then re-use that connection for relying infrastructure, such as `illuminate/database`. Previously, this was not possible because after migrations were run (via command-line by hand, or by the test-suite) the connection is dropped and the in-memory database goes away. The way we get around this is by executing Phinx as a console application in PHP, rather than from the command-line. If we do this, we are able to extract a reference to the instance of PDO it used to do migrations and can inject that anywhere that will take it for further work. This is what I have done here in [`DatabaseTestCase`](https://github.com/mdwheele/opencfp/blob/display-airport-info/tests/DatabaseTestCase.php).

Other small things:

- Added a trait for object immutability.
- Added a new Phinx environment called `memory`.
- Fixed an old migration that was incompatible with Sqlite3 through the use of `CONCAT` function. There are no backwards incompatible changes here as without this fix, a user cannot run OpenCFP on Sqlite3, period.

### CODE REVIEW

**Comment by mdwheele** [comment]
I'll sort this out tonight. Getting reporting differences between local and Travis regarding Phinx environment.

**Comment by mdwheele** [comment]
Sweet. I've got it figured out. I just need to pass additional configuration to `ArgvInput` to specify configuration path for the execution of `PhinxApplication` within the test case. Will do this next break I get and rebase the "test builds" on Travis.

**Comment by mdwheele** [comment]
Alright, this PR is now passing and is ready for review on content of work.

**Comment by chartjes** [comment]
Thanks @mdwheele

**Pull request merged**
