### PR TITLE
Feat: Remake the dockerfile configuration

### PR DESCRIPTION
**Pull request by BoutValentin**
Need to work on nginx compatibilities

This PR

* [x] 
* [ ] 
* [ ] 

Follows #.
Related to #.
Fixes #.

### CODE REVIEW

**Comment by chartjes** [comment]
Thanks for cleaning this up.

**Comment by toofff** [comment]
NOOOOOOOOO, this PR is Draft, is not finish

**Comment by chartjes** [comment]
Ah, it's okay! Just keep working on it and I will deal with anyone else complaining about it not working.

**Comment by toofff** [comment]
@chartjes OK we continue but we still had a lot of work to do on it, it would be better to do a revert of commit on your side, because it will take us a little more time.

**Pull request merged**
