### PR TITLE
Adds pre-flight check to DatabaseServiceProvider

### PR DESCRIPTION
**Pull request by mdwheele**
This is quality-of-life work in response to the issues in #179. The service provider for our database connection through PDO now does a final check on the connection before registering PDO in the service container.

I implemented this as a "unit" test, but it's not really a unit test because PDO isn't mocked. I think that in this case (because we're getting some odd behaviour out of PDO regarding "invalid" DSNs) it is appropriate to not mock it.  If you would like me to move the test somewhere else or put it in an "integration" group, let me know and I'll adjust.

Current implementation fatally errors when invalid DSN provided (similar to what happens if you forget to `composer install` etc etc.):
```
Fatal error: Uncaught exception 'Exception' with message 'There was a problem connecting to the
 database. Make sure to use proper DSN format. See: http://php.net/manual/en/pdo.connections.php' 
in /var/www/html/opencfp/classes/OpenCFP/Provider/DatabaseServiceProvider.php:37 Stack trace: 
#0 /var/www/html/opencfp/classes/OpenCFP/Provider/DatabaseServiceProvider.php(20): OpenCFP\Provider\DatabaseServiceProvider->checkConnection(Object(PDO)) 
#1 /var/www/html/opencfp/vendor/silex/silex/src/Silex/Application.php(169): OpenCFP\Provider\DatabaseServiceProvider->register(Object(OpenCFP\Application)) 
#2 /var/www/html/opencfp/classes/OpenCFP/Application.php(51): Silex\Application->register(Object(OpenCFP\Provider\DatabaseServiceProvider)) 
#3 /var/www/html/opencfp/web/index.php(11): OpenCFP\Application->__construct('/var/www/html/o...', Object(OpenCFP\Environment)) 
#4 {main} thrown in /var/www/html/opencfp/classes/OpenCFP/Provider/DatabaseServiceProvider.php on line 37
```

Hope this helps!

### CODE REVIEW

**Comment by mdwheele** [comment]
Done! Can rebase white space fix out before merge if you want. Editing from phone because I'm on the move, haha.

**Comment by mdwheele** [comment]
Eh. I'll take another look at it when I get to a terminal. I see tests are failing for Travis and not for me locally. I'll ping when fixed.

**Comment by mdwheele** [comment]
Okay. Let me know if you want a rebase before merge!

**Comment by chartjes** [comment]
Yeah, rebase it to remove the extra spaces and I will merge it in

**Comment by chartjes** [comment]
Thanks @mdwheele

**Pull request merged**
