### PR TITLE
Export feature

### LINKED ISSUE #257: Add export talks list feature
- [ ] Export list of talks to CSV (one talk per row) with all information including speaker bio etc.
- [ ] Export list of anonmised talks to CSV (Talk title, length, category and abstract)
- [ ] Export list of email addresses for accepted talks
- [ ] Export list of email addresses for speakers with only rejected talks

### PR DESCRIPTION
**Pull request by michaelcullum**
Closes #257

Sample CSVs: https://www.dropbox.com/sh/e1pfioq7fcjmli0/AADUx-0_txio4iqhmS-Gszgaa?dl=0

This allows for:
* A full list of talks complete with speaker info (one talk a row)
* A full list of talks anonymised (Speaker info fields, slides and 'More Information' removed)
* A list of all talk names, whether they were selected, speaker names and emails for use in sending acceptance/rejection emails
* A list of all selected talks with full information including speaker info

What must be done before merge
- [ ] It need an icon for the admin menu on the left

There is some neatening up that should probably be done but this is fully functional and I'm not sure if/when I'll have a chance to neaten it up so if someone wants to continue this feel free. I can certainly add on a revised navigation icon however if someone can make the icon (I'm no designer).

### CODE REVIEW

**Comment by michaelcullum** [comment]
@chartjes

**Comment by mdwheele** [comment]
I'm interested in continuing this work and will do so after #258 is reviewed / merged as that is a pretty hefty PR. I have interest in seeing this work through as it relates to providing #236 as well.

**Comment by chartjes** [comment]
I'm working on looking at @jakefolio's huge patch today

On Sun, Nov 15, 2015, at 06:54 PM, Dustin Wheeler wrote:
> I'm interested in continuing this work and will do so after #258[1] is
> reviewed / merged as that is a pretty hefty PR. I have interest in
> seeing this work through as it relates to providing #236[2] as well.


> — Reply to this email directly or view it on GitHub[3].


>



Links:

  1. https://github.com/opencfp/opencfp/pull/258
  2. https://github.com/opencfp/opencfp/issues/236
  3. https://github.com/opencfp/opencfp/pull/260#issuecomment-156873186

**Comment by chartjes** [comment]
@mdwheele Do you want to merge this in or will you grab it and keep working on it?

**Comment by chartjes** [comment]
Thanks @michaelcullum

**Comment by chartjes** [comment]
Sorry, had to revert merging this in because the tests are failing. If you get all the tests passing then I will support merging it back in.

**Comment by michaelcullum** [comment]
It's just braces on new lines which should be on the same line in a couple of places.

**Comment by chartjes** [comment]
Okay, if you could fix those up and then resubmit it?

On Thu, Nov 19, 2015, at 08:37 PM, Michael C. wrote:
> It's just braces on new lines which should be on the same line in a
> couple of places.


> — Reply to this email directly or view it on GitHub[1].


>



Links:

  1. https://github.com/opencfp/opencfp/pull/260#issuecomment-158254047

**Pull request merged**
