### PR TITLE
Enhancement: code coverage

### PR DESCRIPTION
**Pull request by BackEndTea**
This PR adds coverage annotations to all tests to show what they are actually testing.

### CODE REVIEW

**Comment by localheinz** [comment]
@BackEndTea 

How about this instead:

* we explicitly split the tests into unit and integration tests

```
tests
├── Integration
└── Unit
```

* we ensure a 1:1 mapping between system under test and test class for unit tests
* we collect coverage only when running unit tests

Then

* we don't need to add any `@covers` or `$coversNothing` annotations
* we never collect accidental coverage
* we speed up the tests (as suggested earlier)

What do you think?

Alternatively, we can also enable the `php_unit_test_class_requires_cover` fixer, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/tree/v2.8.2#usage>

>**php_unit_test_class_requires_covers**
>
>Adds a default `@coversNothing` annotation to PHPUnit test classes that have no `@covers*` annotation.

**Comment by localheinz** [comment]
@BackEndTea 

See #629.

**Comment by BackEndTea** [comment]
@localheinz 
I like the idea of splitting up the tests between unit and integration tests, though
> we ensure a 1:1 mapping between system under test and test class for unit tests

Is a lot easier said then done. Therefore id like to split them up like you are doing in #629, but still keep the ```@covers``` annotations. And enabling ```php_unit_test_class_requires_covers``` looks like a good idea.

**Comment by localheinz** [comment]
@BackEndTea 

Sounds good!

**Comment by BackEndTea** [comment]
Closing this in favor of #629

**Pull request closed without merging**
