### PR TITLE
Symfony/security-csrf add, ENV add, date formats, and readme update

### PR DESCRIPTION
**Pull request by adamculp**
A few items required for functionality.

### CODE REVIEW

**Comment by chartjes** [comment]
@adamculp Could you add a note to the documentation that we are now setting a default environment value? Some people might miss this and end up with a production install being in dev mode

**Comment by adamculp** [comment]
Very valid point. I see a few things that could be updated in the README. I'll add the note on env value as well and add it to this request.

**Comment by mdwheele** [comment]
Hey @adamculp, wanted to give you a heads up that `CFP-ENV` should be `CFP_ENV`. Here's where that is being resolved: https://github.com/opencfp/opencfp/blob/master/classes/OpenCFP/Environment.php#L49-L54

It's currently working for ya because it's defaulting to `development`.

**Comment by adamculp** [comment]
Thanks. Will note that when updating the readme.

**Comment by adamculp** [comment]
OK, made some updates. Look OK? Ready to merge in?

**Comment by chartjes** [comment]
Thanks @adamculp

**Pull request merged**
