### PR TITLE
Fix CFP closing time

### LINKED ISSUE #336: OpenCFP starts denying talk submission before CFP closes
Note the time on https://github.com/opencfp/opencfp/blob/d0bac4cb822caacd0cd9d9f6067f3dd91ea71d0b/classes/Http/Controller/DashboardController.php#L49 vs https://github.com/opencfp/opencfp/blob/master/classes/Http/Controller/TalkController.php#L24

### PR DESCRIPTION
**Pull request by michaelcullum**
Fix #336

### CODE REVIEW

**Comment by mdwheele** [comment]
Change was made to variable in method body. Please change either the method signature or revert this part of the patch. Looks good otherwise.

**Comment by michaelcullum** [comment]
@mdwheele Yeah I'd just spotted that after making the PR. Fixed.

This appears to be a regression from a recent change.

**Comment by michaelcullum** [comment]
Ah yes. Regression from 5f17d2d072a3e37b4f94a895cd037c156a193444

**Comment by mdwheele** [comment]
Looks good to me. I'll merge this after adding a test for this. This type of thing should have been caught easily to prevent that regression. We're making progress for sure. 

Thanks for the help.

**Comment by mdwheele** [comment]
Closing this in favor of a continuance of this in #339. Thanks for the patch @michaelcullum!

**Pull request closed without merging**
