### PR TITLE
Adds new units tests and makes one test less brittle

### PR DESCRIPTION
**Pull request by andrewscaya**
This PR

* Adds a new test for the Environment class
* Adds a test to check OpenCFP\Console\Application's getContainer method
* Adds a test to check the OpenCFP\Http\Form\Login object

### CODE REVIEW

**Comment by chartjes** [comment]
Looks good but we use Mockery for the doubles. Fix that up and I'll merge this

**Comment by andrewscaya** [comment]
Mockery is now used to create all of the test doubles.

**Comment by mdwheele** [comment]
Thanks @andrewscaya!

**Comment by andrewscaya** [comment]
@mdwheele You're very welcome.  Glad to be a part of this project!  I plan to keep it coming in the next few weeks.  Cheers!

**Pull request merged**
