### PR TITLE
UI/UX Improvements

### PR DESCRIPTION
**Pull request by mdwheele**
This PR is 🔥 

I need to wrap a few things before this should be merged. I would appreciate others checking this out and poking around. A lot has changed.

First, we got a new logo from @elioqoshi and that inspired a good bit of the visual design.

We have a new login page!

image

The signup process has been simplified and stretched out. After this update, new speakers register with an email address and password. They don't have to fill out their entire profile. Eventually, we'll add social logins (GitHub, Facebook, Google, etc.)

image

When I register as `anonymous@example.com`, this is the first thing I see:

image

I fill out my profile...

image

And then I'm dropped onto the "Dashboard". Notice there's progression here and OpenCFP guides me through the process. 

image

I can "Get Started" by submitting a talk:

image

I can review a list of talks I've submitted to this conference:

image

That's about it for *Speakers*. The Admin dashboard got a bit of a face-lift as well. Let's log in as an administrator. The promote/demote command-line tools work exactly the same. This is the new "Admin Dashboard"

image

Pretty much the same information, just got rid of tables and cleaned up a few things. I feel like this makes it easier to see what's happening at a glance.

I dropped / collapsed a few features. We used to have a "Review Talks" page. This was collapsed as a filter into the "Talks" page:

image

It works exactly the same. Talks have to be rated and then they're sorted by number of 👍 . It just didn't make sense to keep a whole route + controller + template stack for what was effectively a filter. 

Similarly, we used to have an "Admin" page that listed all instance administrators. I collapsed this into Speakers and dropped the relevant controller, routes and templates.

image

Check out the flash messages... oh snap.

Reviewing talks feels pretty badass now:

image

All the same stuff, just re-organized a bit and cleaned up. The previous "is this my best talk" and "sponsor" flags on talks are now icons:

image

Leaving the admin side of things, the front-end pages got restyled:

image

The background is Chicago... and it matches what shows up on the login/register pages. This could be made customize-able via config in the future so that you can could have it match a conference's venue. Also notice the "Fork me on GitHub". That points to https://github.com/opencfp/opencfp.

There are some less-glamorous changes:

- Templates are now in `resources/views` (previously `templates`)
- We're using https://tailwindcss.com. This saved me sooooo much time. I also thought it'd be nice to have an early example for a project that's going to become very popular and have lots of folks asking "How to do X in Tailwind?" We're also using Sass and the compiled CSS is committed to be ready out of the box. Doing this work makes customizing / theming OpenCFP much much much easier. There are still improvements that could be made here, for sure.
- Started using Illuminate validators to check inputs to controllers rather than heavy Form objects. This should be used for request validation, not domain.
- Using Laravel mix to compile Sass/tailwind. Makes dealing with webpack super simple.

There are some things to finish before merging:

* [ ] Document how to compile CSS / tailwindcss
* [x] Verify this updates over existing installs without issue
* [x] This being a pretty substantial visual reworking, now is a good time to go through and make sure we're visually representing the most important information adequately.

Anywho... that's all.

🔥 🔥 🔥 🔥 🔥

### CODE REVIEW

**Comment by mdwheele** [comment]
Codeclimate is aaaaaaaaaaaaaaaaaaaangry.

**Comment by localheinz** [comment]
@mdwheele 

Just from inspecting the screenshots, this looks great so far. Chicago, eh?

**Comment by mdwheele** [comment]
> The only issue I am wondering about is in terms of semantic versioning is this simply v1.1.0 or is it v2? I don't think we're doing anything that breaks backwards compatibility in terms of functionality...

It's worth some additional scrutiny, but I don't think there are any BC breaks with existing installs. The expectation is that you should be able to update normally, run migrations and be good to go. End-users shouldn't even need to install front-end libraries as CSS is source controlled with project.

**Comment by mdwheele** [comment]
I've squashed this branch after making sure Codeclimate checks were satisfied.

**Comment by elioqoshi** [comment]
Looks fabulous! Great work and amazing how swiftly you did these :)
Are the changes live already?

**Comment by mdwheele** [comment]
@elioqoshi All you! The logo you gave us inspired making something better to fit it :smile: 

The changes were merged and released in [v1.2.0](https://github.com/opencfp/opencfp/releases/tag/v1.2.0). I need to update the `README.md` to include logo + new screenshots.

non-sequitur: I just wanted to point out that the talk data in the screenshots are **NOT** my talks. I went out to a few running conferences (sunshine, I think) and grabbed a few talks. :+1:

**Pull request merged**
