### PR TITLE
online conference dashboard fix

### PR DESCRIPTION
**Pull request by pmeth**
removing transportation and hotel display on dashboard if online conference is selected
removing twitter link if empty

### CODE REVIEW

**Comment by mdwheele** [comment]
@pmeth Would you mind adding a test for this [here](https://github.com/opencfp/opencfp/blob/master/tests/unit/controllers/DashboardControllerTest.php)? Tests are kinda hairy sometimes, so let me know if this is a problem and I can pitch in.

**Comment by pmeth** [comment]
This test would involve mocking the “site” twig variable which gets injected through the TwigServiceProvider based off the config[‘application’] array.  I’m not sure how to mock that, or if not mock it then at least change its value.  Do you have any advice?

**Comment by mdwheele** [comment]
Sure thing. I'm on the way home from work right now but can lend a hand when I arrive.

Also saw another thing we could improve as part of this:

image

[The speaker's airport](https://github.com/opencfp/opencfp/blob/dashboard-fix-online-conf/templates/admin/speaker/view.twig#L15) could be hidden if it is an online conference.

**Comment by mdwheele** [comment]
@pmeth See comparison [here](https://github.com/opencfp/opencfp/compare/dashboard-fix-online-conf...mdwheele:dashboard-online-conf-test) for an example of writing such a test. Writing unit tests for the current codebase has TONS of room for improvement; hence the struggle / efforts to factor a lot of infrastructural dependencies out. Anywho, in the short-term, I could help by whipping together some of the more common test double necessities as "scenarios" we could attach via trait, but that's obviously outside scope of this. I'll create an issue.

That commit should be merge-able to this PR so I would grab it and riff on it as an example for the other tests. What I have covers most of the speaker dashboard changes.

**Comment by mdwheele** [comment]
I went ahead and pushed this commit onto the `upstream` branch to save a step. Feel free to rebase or whatever. I'm going to make time for an hour or so tonight to get this and another PR merged in. If I don't hear from you by then, I hope you're amenable to me pushing here!

**Comment by pmeth** [comment]
Ya go ahead. I won't be able to put more time into this over the next few
days anyway.

**Pull request merged**
