### PR TITLE
Fix: Classname should end in Test

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] renames `TalksControllerTests` to `TalksControllerTest`

### CODE REVIEW

**Comment by localheinz** [comment]
@chartjes @mdwheele @pmeth 

The build failing here indicates that the test has never actually been run before, doesn't it?

See https://travis-ci.org/opencfp/opencfp/builds/112438321.

**Comment by mdwheele** [comment]
That seems correct as the test-case previously ended with `Tests` rather than `Test`. See note at https://phpunit.de/manual/current/en/organizing-tests.html#organizing-tests.filesystem.

It'd probably be best to go ahead and resolve the issue as part of this PR after determining expected behaviour.

**Comment by localheinz** [comment]
@mdwheele 

Will have a look tomorrow!

Can you do me a big favour, though, and have a look at #368? Will make it a lot easier to run the tests locally!

**Comment by mdwheele** [comment]
Done!

**Comment by localheinz** [comment]
Thank you, @mdwheele!

**Comment by localheinz** [comment]
@mdwheele 

Do you want to take a look again?

**Comment by chartjes** [comment]
This has been hanging around long enough...

**Pull request merged**
