### PR TITLE
Enhancement: Enable declare_strict_types fixer

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] enables the `declare_strict_types` fixer
* [x] runs `make cs`
* [x] fixes failing tests

💁‍♂️ For reference, see https://github.com/FriendsOfPHP/PHP-CS-Fixer/tree/v2.8.3#usage:

>**declare_strict_types** [`@PHP70Migration:risky`, `@PHP71Migration:risky`]
>
>Force strict types declaration in all files. Requires PHP >= 7.0.
>
>*Risky rule: forcing strict types will stop non strict code from working.*

### CODE REVIEW

**Comment by localheinz** [comment]
@BackEndTea @chartjes @mdwheele 

While this is still a work in progress and potentially a risky change, what do you think about it?

**Comment by BackEndTea** [comment]
I like the idea of strict types. Should improve the overall quality.

**Comment by chartjes** [comment]
Also a big fan of strict types, especially in an open source project

👍

**Comment by localheinz** [comment]
Thank you, @chartjes!


Let me resolve the conflicts real quick.

**Comment by chartjes** [comment]
@localheinz I didn't see any when I merged so we're good!

**Pull request merged**
