### PR TITLE
Correct the route for profile update after invalid entry; fixes #214

### LINKED ISSUE #214: Profile edit with failed validation is unrecoverable.
Will be writing a test and patch for this. Just wanted to jot down notes. I found this while working on #213. 

**Steps to reproduce**

1. Have an account with OpenCFP
2. Authenticate
3. Edit Profile
4. Remove `last_name`, a required attribute. Attempt save.
5. See validation error (`Error: Last name was blank or contained unwanted characters`).
6. Add a valid `last_name` and save.
7. Expected SUCCESS; Actual: FAILURE with message:

```
Notice: No route found for "POST /profile/edit/1": Method Not Allowed (Allow: GET) in /var/www/html/opencfp/classes/OpenCFP/Application.php on line 257
array(9) { ["id"]=> string(1) "1" ["email"]=> string(17) "speaker@example.org" ["first_name"]=> string(6) "Dustin" ["last_name"]=> string(5) "Wheel" ["company"]=> string(0) "" ["twitter"]=> string(0) "" ["speaker_bio"]=> string(0) "" ["airport"]=> string(0) "" ["speaker_info"]=> string(0) "" }
Fatal error: Uncaught exception 'Twig_Error_Runtime' with message 'Variable "current_page" does not exist in "layouts/default.twig" at line 12' in /var/www/html/opencfp/vendor/twig/twig/lib/Twig/Template.php:366 Stack trace: #0 /var/www/html/opencfp/vendor/twig/twig/lib/Twig/Environment.php(332) : eval()'d code(39): Twig_Template->getContext(Array, 'current_page') #1 /var/www/html/opencfp/vendor/twig/twig/lib/Twig/Template.php(313): __TwigTemplate_14f0f6d536f743574f60b2ccdf689eae16e9096fb92d84f7ba0523871b587c7d->doDisplay(Array, Array) #2 /var/www/html/opencfp/vendor/twig/twig/lib/Twig/Template.php(287): Twig_Template->displayWithErrorHandling(Array, Array) #3 /var/www/html/opencfp/vendor/twig/twig/lib/Twig/Environment.php(332) : eval()'d code(24): Twig_Template->display(Array, Array) #4 /var/www/html/opencfp/vendor/twig/twig/lib/Twig/Template.php(313): __TwigTemplate_a0bdbe8b1025103004da9dc56693675f96fbc6667585435bd80febef0eff416a->doDisplay(Array, Array) #5 /var/www/html/opencfp/vendor/twig/twig/lib/Twig/Template.php(28 in /var/www/html/opencfp/vendor/twig/twig/lib/Twig/Template.php on line 366
```

**Probable fix**

When edit page is loaded, form action is `POST /profile/edit`. After validation errors are shown, form action is incorrectly `POST /profile/edit/1`. There is no route registered for this pattern. Correct the URL generation when validation errors are shown to resolve.

Manual edit of markup before submitting does indeed resolve the issue.

### PR DESCRIPTION
**Pull request by yitznewton**
As far as I can tell, the `user_edit` route was always wrong here; there's no reason we would want a form pointing at that route.

This is all in the controller, and there's no controller test at present; not sure whether I should set one up for this small degree of change?

### CODE REVIEW

**Comment by mdwheele** [comment]
Testing this at the controller level proved difficult last time I tried and eventually gave up because in the time it took to string everything together just right, I could have factored this use-case out into an application service method and simply tested that. 

That's honestly the approach I've been taking when choosing to work on OpenCFP recently. We migrated enough of the legacy to a "newer" structure to facilitate sharing code between the Web and API gateways (*just* enough to get the API shipped). 

I'd be fine merging this on the condition that we create an issue to track a longer-term refactor of use-cases into services. I want to be able to eventually ask the question "Where does user profile updates happen?" and be able to quickly locate that; understanding that the controllers for web and API are just mapping those service calls to HTTP.

In the mean time... this is a bugfix for an annoying issue, for sure.

**Comment by yitznewton** [comment]
WRT making an issue about extraction of use-cases as objects, do y'all have any sort of iteration or release planning, or is development done ad hoc? If there's some contributor's corner where you already lay that stuff out, you can point me over there :grin:

**Comment by mdwheele** [comment]
It's all ad hoc, but would love to sit down to create a "contributor's corner". I get an itch every now and then to bust out a bunch of work and then I spend time on other projects for a while. Maybe we can schedule some time in IRC at some point to discuss? A public Trello board or something more or less light-weight would be great. Let me know!

**Comment by chartjes** [comment]
@yitznewton @mdwheele Thanks folks

**Pull request merged**
