### PR TITLE
Fix: Order use statements

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] enables `ordered_use` fixer
* [x] runs `make cs`

Follows #242.

:information_desk_person: See https://github.com/FriendsOfPHP/PHP-CS-Fixer/tree/1.11#usage:

> **ordered_use [contrib]**
Ordering use statements.

### CODE REVIEW

**Comment by localheinz** [comment]
@chartjes @mdwheele 

How about enabling more fixers, step by step?

**Comment by mdwheele** [comment]
What if we turned on PSR2? I could take the time to work through any breaky breaky. Then you won't have to go fix by fix.

**Comment by mdwheele** [comment]
Whoops. Looks like we already are. I'm down to add more step by step but wouldn't want to go overboard. PSR2 is pretty much good enough from my perspective but that's about the extent of my usage of phpcs honestly.

**Comment by localheinz** [comment]
@mdwheele 

There's a ton of useful fixers which fix issues which go beyond PSR-2, and help maintaining a consistent coding style. Since it's not a lot of work, I wouldn't mind opening a few PRs, then you can decide whether you like the result, what do you think?

**Comment by mdwheele** [comment]
Sounds great. Thanks @localheinz!

**Pull request merged**
