### PR TITLE
Fix: Flatten directory structure

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] flattens the directory structure

Follows #344.

### CODE REVIEW

**Comment by mdwheele** [comment]
Going to look at this one more closely when I get home. Looks good but I'm on mobile at the moment and want to make sure this passes when integrated with your other PRs.

**Comment by mdwheele** [comment]
Actually, just saw conflict. It's probably trivial but could you go ahead and rebase this on master so we can see integrated build?

**Comment by localheinz** [comment]
@mdwheele 

Totally, will do as soon as I'm out of the :bath:!

**Comment by mdwheele** [comment]
TMI!!!

**Comment by localheinz** [comment]
@mdwheele 

Hehe, sorry - rebased!

**Comment by mdwheele** [comment]
Looking at this now. Just got internet back last night after the east coast Snowpocalypse

**Comment by mdwheele** [comment]
Looks good. Thanks @localheinz!

**Comment by localheinz** [comment]
@mdwheele 

:snowman:

**Pull request merged**
